import { Outfit } from "next/font/google";
import "../globals.css";

const outfit = Outfit({ subsets: ["latin"] , weight:["400","500","600","700"]});

export const metadata = {
  title: "EduTechEvent",
  description: "Generated by Mezbah",
};

export default function ContactLayout({ children }) {
  return <div className={outfit.className}>{children}</div>;
}
